create table flow (id integer not null, shareable boolean, user_id integer, created_date datetime(6), version bigint, description varchar(255), salt_nonce varchar(255), title varchar(255), uuid varchar(255), wallet_provider varchar(255), primary key (id)) engine=InnoDB;
create table flow_seq (next_val bigint) engine=InnoDB;
insert into flow_seq values ( 1 );
create table invitation (id integer not null, invited_by_id integer, invitee_id integer, created_date datetime(6), expiry_date datetime(6), version bigint, code varchar(255), identity varchar(255), primary key (id)) engine=InnoDB;
create table invitation_allowance_seq (next_val bigint) engine=InnoDB;
insert into invitation_allowance_seq values ( 1 );
create table invitation_seq (next_val bigint) engine=InnoDB;
insert into invitation_seq values ( 1 );
create table invitation_allowance (code_invite_limit integer, id integer not null, idenity_invite_limit integer, user_id integer not null, version bigint, primary key (id)) engine=InnoDB;
create table user (allowed boolean, flow_id integer, id integer not null, locked boolean, created_date datetime(6), last_seen datetime(6), version bigint, display_name varchar(255), profile_image varchar(255), signer varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_seq (next_val bigint) engine=InnoDB;
insert into user_seq values ( 1 );
create table wallet (deployed boolean, flow_id integer not null, id integer not null, network integer, created_date datetime(6), version bigint, address varchar(255), wallet_version varchar(255), primary key (id)) engine=InnoDB;
create table wallet_seq (next_val bigint) engine=InnoDB;
insert into wallet_seq values ( 1 );
create index IDX4hu30fxqo5t3xvipenkwke32d on flow (user_id);
create index IDX8ddly8js9x7rq1j0i2n7y2e8d on flow (uuid);
alter table flow add constraint UK_8ddly8js9x7rq1j0i2n7y2e8d unique (uuid);
alter table invitation add constraint UKayqqf0gxgnff95esnigv1m2i8 unique (identity);
alter table invitation add constraint UK_ld4xi0kv9nek3qvxbs6f0ruww unique (invitee_id);
alter table invitation_allowance add constraint UK_9j899qpeto64bk9ih1yynv5ht unique (user_id);
alter table user add constraint UK3lbait4oerhndfs8i8n49yi25 unique (signer);
alter table user add constraint UKsb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table user add constraint UKpnrrew2o71m330w38p0ypwjvn unique (display_name);
alter table user add constraint UK_fatdl380fi4sd3xkm212n5na0 unique (flow_id);
alter table wallet add constraint UKcql1yqlqa72l11fc40nd136q8 unique (network, address);
alter table flow add constraint FKg03065o9220oecw1s2yn9quvd foreign key (user_id) references user (id);
alter table invitation add constraint FKmajf0gle9nc4lupdmylkhac8b foreign key (invited_by_id) references user (id);
alter table invitation add constraint FKdj1cemychywmmsfobv215slrm foreign key (invitee_id) references user (id);
alter table invitation_allowance add constraint FKnphpgqpiqpvyr8rdu9yyllk8m foreign key (user_id) references user (id);
alter table user add constraint FKj19fi9nb94ak2l0ufe7lej6a4 foreign key (flow_id) references flow (id);
alter table wallet add constraint FKi9pspiqvtj8j368iehxdd7k6s foreign key (flow_id) references flow (id);
