query getTop30Followings($identity: Identity!, $limit: Int) {
    SocialFollowings(
        input: {limit: $limit, filter: {dappName: {_eq: farcaster}, identity: {_eq: $identity}}, blockchain: ALL}
    ) {
        Following {
            followingAddress {
                addresses
                socials(input: {filter: {dappName: {_eq: farcaster}}}) {
                    profileName
                }
            }
        }
    }
}